---
- hosts: servers
  include_vars: vars.yml
  gather_facts: false
  sudo: true
  sudo_user: "{{ project_name }}"

  tasks:
  - name: Pull sources from repository
    git: repo={{ project_repo }} dest={{project_root}}/code/src version={{ branch }}
    only_if: "$vm == 0"
    notify:
      - restart web services

  - name: Build project
    shell: export GOPATH=`pwd`/go && go build hello

  - name: run it :D
    shell: nohup sudo ./hello &
